### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by lrnzdc3696** [dracula/git#3] opened 2022-07-21 10:25 UTC
So I recently tried to get dracula for git I tested what the documentation said.
I have dracula theme in my xfce4-terminal and here is my dotfiles https://github.com/LrnzDC3696/dotfiles/blob/main/.gitconfig

without the comment ofcourse. but the theme is not appearing what should I do?

without the comment
![image](https://user-images.githubusercontent.com/77531972/180192129-bbfa4dea-3d46-405a-89ca-41a9ad2a8667.png)

with comment
![image](https://user-images.githubusercontent.com/77531972/180192264-47993702-9536-4eab-8a4a-dfd7eec376dd.png)

**Comment by revagomes** [comment] 2022-08-22 14:13
@LrnzDC3696 
Thanks for the feedback! I haven't tested all Dracula Themes for terminal, so is nice to have your input.

That is caused by differences on color scheme of Dracula Theme for xfce4-terminal and the one I took as reference which is Dracula Theme for Terminator. This last one changes "white" color to "#efa554" as you can see on the screenshot in the README file).

That's the reason for having the setting bellow:
https://github.com/LrnzDC3696/dotfiles/blob/main/.gitconfig#L96
```
[color "status"]
  changed = white
```

I suggest you customizing your .gitconfig file and set a different color for the "changed" setting, or leave it blanc so the default color will be used:

Here is an example:
```
[color "status"]
  changed = yellow
```

OR 

```
[color "status"]
  changed =
```

To prevent that to happen on other Dracula Themes for Terminal I'll update the default setting of the changed status to be Yellow as well so it's safer 👍

**Comment by revagomes** [comment] 2022-08-22 14:29
The master branch is already updated with a fix for it. 
Closing.

**Closed as completed by revagomes** 2022-08-22 14:29 UTC
